apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-pv
  labels:
    type: pgadmin-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "<PGADMIN_PV_VOLUME>"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "<PGADMIN_PVC>"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000M
  selector: 
    matchLabels: 
      type: pgadmin-pv    