# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#replicaCount is the number of replicas required for this service
replicaCount: 1
#namespace is the place for the service to run
namespace: <NAMESPACE>
image:
  # Placeholders will replaced in runtime based on .env file
  repository: k3d-<NAME_LOCALREGISTRY>:<PORT_LOCALREGISTRY>/<IMAGE_NAME_MOBIUSVIEW>
  tag: <IMAGE_VERSION_MOBIUSVIEW>
  pullPolicy: IfNotPresent
deploy:
  fullstack: false
service:
  type: ClusterIP

datasource:
   url: "jdbc:postgresql://<POSTGRESQL_HOST>:<POSTGRESQL_PORT>/<POSTGRESQL_DBNAME_MOBIUSVIEW>"
   username: "<POSTGRESQL_USERNAME>"
   password: "<POSTGRESQL_PASSWORD>"

initRepository:
  enabled: true
  host: "mobius"
  port: "8080"
  documentServer: "vdrnetds"
  defaultSSOKey: "ADASDFASDFXGGEG25585"
  logLevel: "ERROR"
  java:
    opts: ""
   
master:
  persistence:
   enabled: true
   claimName: mobius-pv-claim
   accessMode: ReadWriteMany
   size: 1000M

  mobiusViewDiagnostics:
    persistentVolume:
      enabled: true
      claimName: mobiusview-diagnostic-pv-claim
      accessMode: ReadWriteMany
      size: 1000M
      
  presentations:
    persistence:
      #enabled is the flag to indicate whether presentation persistence claim is required or not    
      enabled: true
      #claimName is the name of the claim created by the user, which will be bound to the mapped persistence volume
      claimName:  mobiusview-presentation-claim
      

asg:
#Enable Kafka audit
  audit:
    topic: audit

spring:
 #Enable Kafka section to enable auditing to kafka. Configure the topic in audit.kafka section  
  kafka:
    bootstrap:
      servers: <KAFKA_BOOTSTRAP_URL>
    security:
      protocol: PLAINTEXT
    producer:
      acks: all
      properties:
        enable:
          idempotence: true

  cloud:
    discovery:
      client:
        simple:
          instances:
            metrics:
              audit:
                uri: http://eventanalytics:8500          