apiVersion: v1
appVersion: "12"
description: ASG Mobius provides an intelligent information management solution that
  delivers content services with a granular policy management foundation to digitally
  transform enterprise content and data according to corporate policies and regulatory
  compliance.
home: https://www.rocketsoftware.com
keywords:
- rockewt
- mobius
- server
- vdrnet
name: mobius-pv
version: 12.0.0
