apiVersion: v1
data:
  Access-Control-Allow-Origin: "*"
  Access-Control-Allow-Credentials: "true"
  Access-Control-Allow-Headers: "*"
  Access-Control-Expose-Headers: "*,Access-Control-Allow-Origin,Access-Control-Allow-Credentials,Accept-Ranges,opaqueRepID,repositoryName,X-OpaqueToken,X-DocumentType,X-Mobius-Page-OriginalHeightPixels,X-Mobius-Page-OriginalWidthPixels,X-Mobius-Page-RenderedHeightPixels,X-Mobius-Page-RenderedScale,X-Mobius-Page-RenderedWidthPixels,X-Mobius-PageClass-Name,X-Mobius-PageClass-Version,X-Mobius-PageNumber,X-Mobius-PageNumber-WithinSectionCode,X-Mobius-PageVersionId,X-Mobius-Subpage-Origin,client-id"
  Access-Control-Allow-Methods: "GET,POST,PUT,DELETE,OPTIONS,HEAD,PATCH"
  Content-Security-Policy: "default-src 'self'; script-src 'self'  'sha256-wSk7Pac68P5NGz0ckYIUSA8nd7eh8zkveKcseL24KB0='; img-src 'self' data:; style-src 'self' 'unsafe-inline';"
  X-Content-Type-Options: "nosniff"
kind: ConfigMap
metadata:
  name: custom-add-headers
  namespace: ingress-nginx