spring:
  main:
    web-application-type: none
    log-startup-info: "false"
    banner-mode: "off"
  cloud:
    discovery:
      client:
        simple:
          instances:
            repositories:
              - uri: ${asg.mobius.archive.url:http://localhost:8080/mobius }
            archivewrite:
              - uri: ${asg.mobius.archive.url:http://localhost:8080/mobius }
            mobiusarchivedelete:
              - uri: ${asg.mobius.archive.url:http://localhost:8080/mobius }
            mobiusarchivemigrate:
              - uri: ${asg.mobius.archive.url:http://localhost:8080/mobius }
            mobiusftindexes:
              - uri: ${asg.mobius.archive.url:http://localhost:8080/mobius }
            mobiusdbxmlentities:
              - uri: ${asg.mobius.archive.url:http://localhost:8080/mobius }

asg:
  cli:
    config:
      location: ${user.home}/asg/mobius/mobius-cli/application.yaml
  security:
    enabled: true
    unsecured:
      enabled: true
      username: admin