apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mobius.persistentVolume.volumeName }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mobius.mobiusDiagnostics.persistentVolume.volumeName }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi