apiVersion: batch/v1
kind: Job
metadata:
  name: mobius12-demo-load
  namespace: zenith
spec:
  template:
    spec:
      containers:
        - name: mobius12-demo-load
          image: registry.rocketsoftware.com/mobius_demo:12.1.0
          env:
            - name: MV_URL
              value: "http://asg-mobius-view:80/mobius"
            - name: MV_REPOSITORY
              value: "Mobius"
            - name: MV_BASIC_AUTH_USER
              value: "admin"
            - name: MV_BASIC_AUTH_PASS #asg!tWo3
              value: "ASG_ENC(c1LpoXEIRe3h7b6TVoDfNP91rGK/9wGM)"
            - name: MV_SECRET_SEC
              value: "5##)MbIPy?%_vFx*5Cm0G15MLc0rV/SK.cY"
            - name: MV_DEMO_DEFINITIONS
              value: "./_XML/CreateAllDataSamplerStructures.xml"
            - name: MV_DEMO_LOAD_DATA
              value: "./_XML/LoadAllDataSamplerContents.xml"
          volumeMounts:
            - mountPath: /mnt/efs
              name:  mobius-pv-storage
      restartPolicy: Never
      volumes:
        - name: mobius-pv-storage
          persistentVolumeClaim: 
            claimName: mobius-efs
  backoffLimit: 4
