apiVersion: v1
kind: PersistentVolume
metadata:
  name: mobius-pv-storage
  labels:
    type: mobius-pv-storage
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "<MOBIUS_PV_VOLUME>"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobius-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000M
  selector: 
    matchLabels: 
      type: mobius-pv-storage    
---      
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mobius-diagnostic-pv-storage
  labels:
    type: mobius-diagnostic-pv-storage
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "<MOBIUS_DIAGNOSTIC_VOLUME>"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobius-diagnostic-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000M
  selector: 
    matchLabels: 
      type: mobius-diagnostic-pv-storage    
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mobius-fts-pv-storage
  labels:
    type: mobius-fts-pv-storage
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "<MOBIUS_FTS_VOLUME>"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobius-fts-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000M
  selector: 
    matchLabels: 
      type: mobius-fts-pv-storage      