kind: Secret
apiVersion: v1
metadata:
  name: mobius-license
  labels:
    app.kubernetes.io/name: {{ include "mobiusview.name" . }}
    helm.sh/chart: {{ include "mobiusview.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  license: MDFNT0JJVVM1MjQ2NEE0NjRDNEJDOTU4NTk1MTgzODE5MDhGQUVBNDQzNEY0NjUxNUU1MzUzOTY4MTk1NUI0NTRENjI0MDUzNDU1NjU2NDM1MTQ3MUQ0NTREMTI0MDUzMDM1NjU2NzI1MTQ3NTk0NTREMTY0MDUzMDU1NjU2MEI1MTQ3MEU0NTRENjA0MDUzN0M1NjU2MEQ1MTQ3MTU0NTREMTA0MDUzNjU1NjU2MDM1MTQ3MEE0NTREMDU0MDUzMTM1NjU2MDk1MTQ3MkE0NTREMkE0MDUzMTU1NjU2MUQ1NjQyQkI1NDRGNEEwOTU0NTRBNEE3QTc0NDQ1NEIwQzRBNEZCMkEyQTAzNjU0NTY1OTQzNDhEOUI0ODY=