apiVersion: v1
kind: Service
metadata:
  name: {{ include "mobiusview.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mobiusview.name" . }}
    helm.sh/chart: {{ include "mobiusview.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    getambassador.io/config: |
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.ports.targetPort }}
      protocol: {{ .Values.ports.protocol }}
      name: {{ .Values.ports.name }}
  selector:
    app.kubernetes.io/name: {{ include "mobiusview.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
