kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.mobius.rds.databaseConnectivitySecretName }}
  labels:
    app.kubernetes.io/name: {{ include "mobius.name" . }}
    helm.sh/chart: {{ include "mobius.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}  
data:
  #Value is mobiusserver12
  user: bW9iaXVzc2VydmVyMTI=
  #Value is mobiusserver12
  schema: bW9iaXVzc2VydmVyMTI=  
  #Value is M0biu$2023
  password: TTBiaXUkMjAyMw==
  #Value is mobius-sales-psql-1.c9oyct7ugcth.us-east-1.rds.amazonaws.com
  endpoint: bW9iaXVzLXNhbGVzLXBzcWwtMS5jOW95Y3Q3dWdjdGgudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  #Value is 5432
  port: NTQzMg==
  #Value is jdbc:postgresql://mobius-sales-psql-1.c9oyct7ugcth.us-east-1.rds.amazonaws.com:5432/eventanalytics
  topicUrl: amRiYzpwb3N0Z3Jlc3FsOi8vbW9iaXVzLXNhbGVzLXBzcWwtMS5jOW95Y3Q3dWdjdGgudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvZXZlbnRhbmFseXRpY3M=
  #Value is eventanalytics
  topicUser: ZXZlbnRhbmFseXRpY3M=
  #Value is M0biu$2023
  topicPassword: TTBiaXUkMjAyMw==