#!/bin/bash

source "$kube_dir/istio/istio.sh"
source "$kube_dir/automationnext/settings.sh"
source "$kube_dir/kafka/kafka.sh"
source "$kube_dir/common/volumes.sh"

set_mobius_settings() {
    ZENITH_MOBIUS_SERVER=${ZENITH_MOBIUS_SERVER:-mobius};
    ZENITH_MOBIUS_PORT=${ZENITH_MOBIUS_PORT:-8080};
    ZENITH_MOBIUS_DOC_SERVER=${ZENITH_MOBIUS_DOC_SERVER:-vdrnetds};
    ZENITH_EXTERNAL_MOBIUS=false;

    if [ "$ZENITH_MOBIUS_SERVER" != "mobius" ]; then
        ZENITH_EXTERNAL_MOBIUS=true;
    fi
}

set_database_common_settings() {
    ZENITH_DATABASE_HOST=${ZENITH_DATABASE_HOST:-}
    ZENITH_DATABASE_PORT=${ZENITH_DATABASE_PORT:-}
}

set_database_common_infra_settings() {
    ZENITH_DATABASE_HOST=${ZENITH_INFRA_DATABASE_HOST:-}
    ZENITH_DATABASE_PORT=${ZENITH_INFRA_DATABASE_PORT:-}
}

set_postgresql_settings() {
    ZENITH_POSTGRESQL_USERNAME=${ZENITH_POSTGRESQL_USERNAME:-postgres}
    ZENITH_POSTGRESQL_PASSWORD=${ZENITH_POSTGRESQL_PASSWORD:-postgres}
    ZENITH_POSTGRESQL_DBNAME_AI=${ZENITH_POSTGRESQL_DBNAME_AI:-zenith_asg_artificial_intelligence}
    ZENITH_POSTGRESQL_DBNAME_DIRECTORY=${ZENITH_POSTGRESQL_DBNAME_DIRECTORY:-zenith_asg_directory_service}
    ZENITH_POSTGRESQL_DBNAME_TENANT=${ZENITH_POSTGRESQL_DBNAME_TENANT:-zenith_asg_tenant_service}
    ZENITH_POSTGRESQL_DBNAME_IDP=${ZENITH_POSTGRESQL_DBNAME_IDP:-zenith_asg_keycloak}
    ZENITH_POSTGRESQL_DBNAME_PORTAL=${ZENITH_POSTGRESQL_DBNAME_PORTAL:-zenith_asg_portal}
    ZENITH_POSTGRESQL_DBNAME_PORTALRT=${ZENITH_POSTGRESQL_DBNAME_PORTALRT:-zenith_asg_portal_realtime}
    ZENITH_POSTGRESQL_DBNAME_PRS=${ZENITH_POSTGRESQL_DBNAME_PRS:-zenith_asg_prs}
    ZENITH_POSTGRESQL_DBNAME_STUDIO=${ZENITH_POSTGRESQL_DBNAME_STUDIO:-zenith_asg_studio}
    ZENITH_POSTGRESQL_DBNAME_PROCESS_ENGINE=${ZENITH_POSTGRESQL_DBNAME_PROCESS_ENGINE:-zenith_asg_process_engine}
    ZENITH_POSTGRESQL_DBNAME_PROCESS_ENGINE_ROOT=${ZENITH_POSTGRESQL_DBNAME_PROCESS_ENGINE_ROOT:-zenith_process_engine_root}
    ZENITH_POSTGRESQL_DBNAME_METRICS=${ZENITH_POSTGRESQL_DBNAME_METRICS:-zenith_asg_metrics}
    ZENITH_POSTGRESQL_DBNAME_POLICY=${ZENITH_POSTGRESQL_DBNAME_POLICY:-zenith_policy}
    ZENITH_POSTGRESQL_DBNAME_MOBIUS=${ZENITH_POSTGRESQL_DBNAME_MOBIUS:-zenith_mobius}
    ZENITH_POSTGRESQL_DBNAME_EVENTANALYTICS=${ZENITH_POSTGRESQL_DBNAME_EVENTANALYTICS:-zenith_eventanalytics}
    ZENITH_POSTGRESQL_DBNAME_MOBIUSVIEW=${ZENITH_POSTGRESQL_DBNAME_MOBIUSVIEW:-zenith_mobiusview}
    ZENITH_POSTGRESQL_DBNAME_AUTHORIZATION=${ZENITH_POSTGRESQL_DBNAME_AUTHORIZATION:-zenith_authorization}
    ZENITH_POSTGRESQL_CONF_MAX_CONNECTIONS=${ZENITH_POSTGRESQL_CONF_MAX_CONNECTIONS:-400}
    ZENITH_POSTGRESQL_CONF_SHARED_BUFFERS=${ZENITH_POSTGRESQL_CONF_SHARED_BUFFERS:-100MB}
}

set_postgresql_infra_settings() {
    ZENITH_POSTGRESQL_USERNAME=${ZENITH_INFRA_POSTGRESQL_USERNAME:-}
    ZENITH_POSTGRESQL_PASSWORD=${ZENITH_INFRA_POSTGRESQL_PASSWORD:-}
    ZENITH_POSTGRESQL_DBNAME_AI=${ZENITH_INFRA_POSTGRESQL_DBNAME_AI:-}
    ZENITH_POSTGRESQL_DBNAME_DIRECTORY=${ZENITH_INFRA_POSTGRESQL_DBNAME_DIRECTORY:-}
    ZENITH_POSTGRESQL_DBNAME_TENANT=${ZENITH_INFRA_POSTGRESQL_DBNAME_TENANT:-}
    ZENITH_POSTGRESQL_DBNAME_IDP=${ZENITH_INFRA_POSTGRESQL_DBNAME_IDP:-}
    ZENITH_POSTGRESQL_DBNAME_PORTAL=${ZENITH_INFRA_POSTGRESQL_DBNAME_PORTAL:-}
    ZENITH_POSTGRESQL_DBNAME_PORTALRT=${ZENITH_INFRA_POSTGRESQL_DBNAME_PORTALRT:-}
    ZENITH_POSTGRESQL_DBNAME_PRS=${ZENITH_INFRA_POSTGRESQL_DBNAME_PRS:-}
    ZENITH_POSTGRESQL_DBNAME_STUDIO=${ZENITH_INFRA_POSTGRESQL_DBNAME_STUDIO:-}
    ZENITH_POSTGRESQL_DBNAME_PROCESS_ENGINE=${ZENITH_INFRA_POSTGRESQL_DBNAME_PROCESS_ENGINE:-}
    ZENITH_POSTGRESQL_DBNAME_PROCESS_ENGINE_ROOT=${ZENITH_INFRA_POSTGRESQL_DBNAME_PROCESS_ENGINE_ROOT:-}
    ZENITH_POSTGRESQL_DBNAME_METRICS=${ZENITH_INFRA_POSTGRESQL_DBNAME_METRICS:-}
    ZENITH_POSTGRESQL_DBNAME_POLICY=${ZENITH_INFRA_POSTGRESQL_DBNAME_POLICY:-}
    ZENITH_POSTGRESQL_DBNAME_MOBIUS=${ZENITH_INFRA_POSTGRESQL_DBNAME_MOBIUS:-}
    ZENITH_POSTGRESQL_DBNAME_MOBIUSVIEW=${ZENITH_INFRA_POSTGRESQL_DBNAME_MOBIUSVIEW:-}
    ZENITH_POSTGRESQL_DBNAME_EVENTANALYTICS=${ZENITH_INFRA_POSTGRESQL_DBNAME_EVENTANALYTICS:-}
    ZENITH_POSTGRESQL_DBNAME_AUTHORIZATION=${ZENITH_INFRA_POSTGRESQL_DBNAME_AUTHORIZATION:-}
}

set_oracle_settings() {
    ZENITH_ORACLE_CONNECTDATA_SERVICENAME=${ZENITH_ORACLE_CONNECTDATA_SERVICENAME:-}
    ZENITH_ORACLE_CONNECTDATA_SID=${ZENITH_ORACLE_CONNECTDATA_SID:-}
    ZENITH_ORACLE_TNS_ALIAS=${ZENITH_ORACLE_TNS_ALIAS:-orcl_ssl}
   
    if [ "$external_database" == "false" ]; then
        USE_SERVICE_NAME=true
        ZENITH_ORACLE_CONNECTDATA_SERVICENAME=${ZENITH_ORACLE_CONNECTDATA_SERVICENAME:-ORCLPDB1}
    else
        if [ "$ZENITH_ORACLE_CONNECTDATA_SID" != "" ]; then
            USE_SERVICE_NAME=false
        else
            USE_SERVICE_NAME=true
            ZENITH_ORACLE_CONNECTDATA_SERVICENAME=${ZENITH_ORACLE_CONNECTDATA_SERVICENAME:-ORCLPDB1}
        fi
    fi

    ZENITH_ORACLE_USER_AI=${ZENITH_ORACLE_USER_AI:-ai_perm}
    ZENITH_ORACLE_USER_DIRECTORY=${ZENITH_ORACLE_USER_DIRECTORY:-directory_perm}
    ZENITH_ORACLE_USER_TENANT=${ZENITH_ORACLE_USER_TENANT:-tenant_perm}
    ZENITH_ORACLE_USER_IDP=${ZENITH_ORACLE_USER_IDP:-keycloak_perm}
    ZENITH_ORACLE_USER_PORTAL=${ZENITH_ORACLE_USER_PORTAL:-portal_perm}
    ZENITH_ORACLE_USER_PORTALRT=${ZENITH_ORACLE_USER_PORTALRT:-portal_rt_perm}
    ZENITH_ORACLE_USER_PRS=${ZENITH_ORACLE_USER_PRS:-prs_perm}
    ZENITH_ORACLE_USER_STUDIO=${ZENITH_ORACLE_USER_STUDIO:-studio_perm}
    ZENITH_ORACLE_USER_PROCESS_ENGINE=${ZENITH_ORACLE_USER_PROCESS_ENGINE:-process_engine_perm}
    ZENITH_ORACLE_USER_PROCESS_ENGINE_ROOT=${ZENITH_ORACLE_USER_PROCESS_ENGINE_ROOT:-process_engine_perm_Root}
    ZENITH_ORACLE_USER_METRICS=${ZENITH_ORACLE_USER_METRICS:-metrics_perm}
    ZENITH_ORACLE_USER_POLICY=${ZENITH_ORACLE_USER_POLICY:-policies_perm}
    ZENITH_ORACLE_USER_MOBIUS=${ZENITH_ORACLE_USER_MOBIUS:-mobius_server_perm}
    ZENITH_ORACLE_USER_MOBIUSVIEW=${ZENITH_ORACLE_USER_MOBIUSVIEW:-mobius_view_perm}
    ZENITH_ORACLE_USER_EVENTANALYTICS=${ZENITH_ORACLE_USER_EVENTANALYTICS:-eventanalytics_perm}
    ZENITH_ORACLE_USER_AUTHORIZATION=${ZENITH_ORACLE_USER_AUTHORIZATION:-authorization_perm}

    ZENITH_ORACLE_PASSWORD_AI=${ZENITH_ORACLE_PASSWORD_AI:-oracle}
    ZENITH_ORACLE_PASSWORD_DIRECTORY=${ZENITH_ORACLE_PASSWORD_DIRECTORY:-oracle}
    ZENITH_ORACLE_PASSWORD_TENANT=${ZENITH_ORACLE_PASSWORD_TENANT:-oracle}
    ZENITH_ORACLE_PASSWORD_IDP=${ZENITH_ORACLE_PASSWORD_IDP:-oracle}
    ZENITH_ORACLE_PASSWORD_PORTAL=${ZENITH_ORACLE_PASSWORD_PORTAL:-oracle}
    ZENITH_ORACLE_PASSWORD_PORTALRT=${ZENITH_ORACLE_PASSWORD_PORTALRT:-oracle}
    ZENITH_ORACLE_PASSWORD_PRS=${ZENITH_ORACLE_PASSWORD_PRS:-oracle}
    ZENITH_ORACLE_PASSWORD_STUDIO=${ZENITH_ORACLE_PASSWORD_STUDIO:-oracle}
    ZENITH_ORACLE_PASSWORD_PROCESS_ENGINE=${ZENITH_ORACLE_PASSWORD_PROCESS_ENGINE:-oracle}
    ZENITH_ORACLE_PASSWORD_PROCESS_ENGINE_ROOT=${ZENITH_ORACLE_PASSWORD_PROCESS_ENGINE_ROOT:-oracle}
    ZENITH_ORACLE_PASSWORD_OCR=${ZENITH_ORACLE_PASSWORD_OCR:-oracle}
    ZENITH_ORACLE_PASSWORD_VAULT=${ZENITH_ORACLE_PASSWORD_VAULT:-oracle}
    ZENITH_ORACLE_PASSWORD_METRICS=${ZENITH_ORACLE_PASSWORD_METRICS:-oracle}
    ZENITH_ORACLE_PASSWORD_POLICY=${ZENITH_ORACLE_PASSWORD_POLICY:-oracle}
    ZENITH_ORACLE_PASSWORD_MOBIUS=${ZENITH_ORACLE_PASSWORD_MOBIUS:-oracle}
    ZENITH_ORACLE_PASSWORD_MOBIUSVIEW=${ZENITH_ORACLE_PASSWORD_MOBIUSVIEW:-oracle}
    ZENITH_ORACLE_PASSWORD_EVENTANALYTICS=${ZENITH_ORACLE_PASSWORD_EVENTANALYTICS:-oracle}
    ZENITH_ORACLE_PASSWORD_AUTHORIZATION=${ZENITH_ORACLE_PASSWORD_AUTHORIZATION:-oracle}
}

set_oracle_infra_settings() {
    ZENITH_ORACLE_CONNECTDATA_SERVICENAME=${ZENITH_INFRA_ORACLE_CONNECTDATA_SERVICENAME:-}
    ZENITH_ORACLE_TNS_ALIAS=${ZENITH_INFRA_ORACLE_TNS_ALIAS:-}

    if [ "$external_database" == "false" ]; then
        USE_SERVICE_NAME=true
        ZENITH_ORACLE_CONNECTDATA_SERVICENAME=${ZENITH_ORACLE_CONNECTDATA_SERVICENAME:-ORCLPDB1}
    else
        if [ "$ZENITH_ORACLE_CONNECTDATA_SID" != "" ]; then
            USE_SERVICE_NAME=false
        else
            USE_SERVICE_NAME=true
            ZENITH_ORACLE_CONNECTDATA_SERVICENAME=${ZENITH_ORACLE_CONNECTDATA_SERVICENAME:-ORCLPDB1}
        fi
    fi

    ZENITH_ORACLE_USER_AI=${ZENITH_INFRA_ORACLE_USER_AI:-}
    ZENITH_ORACLE_USER_DIRECTORY=${ZENITH_INFRA_ORACLE_USER_DIRECTORY:-}
    ZENITH_ORACLE_USER_TENANT=${ZENITH_INFRA_ORACLE_USER_TENANT:-}
    ZENITH_ORACLE_USER_IDP=${ZENITH_INFRA_ORACLE_USER_IDP:-}
    ZENITH_ORACLE_USER_PORTAL=${ZENITH_INFRA_ORACLE_USER_PORTAL:-}
    ZENITH_ORACLE_USER_PORTALRT=${ZENITH_INFRA_ORACLE_USER_PORTALRT:-}
    ZENITH_ORACLE_USER_PRS=${ZENITH_INFRA_ORACLE_USER_PRS:-}
    ZENITH_ORACLE_USER_STUDIO=${ZENITH_INFRA_ORACLE_USER_STUDIO:-}
    ZENITH_ORACLE_USER_PROCESS_ENGINE=${ZENITH_INFRA_ORACLE_USER_PROCESS_ENGINE:-}
    ZENITH_ORACLE_USER_PROCESS_ENGINE_ROOT=${ZENITH_INFRA_ORACLE_USER_PROCESS_ENGINE_ROOT:-}
    ZENITH_ORACLE_USER_METRICS=${ZENITH_INFRA_ORACLE_USER_METRICS:-}
    ZENITH_ORACLE_USER_POLICY=${ZENITH_INFRA_ORACLE_USER_POLICY:-}
    ZENITH_ORACLE_USER_MOBIUS=${ZENITH_INFRA_ORACLE_USER_MOBIUS:-}
    ZENITH_ORACLE_USER_MOBIUSVIEW=${ZENITH_INFRA_ORACLE_USER_MOBIUSVIEW:-}
    ZENITH_ORACLE_USER_EVENTANALYTICS=${ZENITH_INFRA_ORACLE_USER_EVENTANALYTICS:-}
    ZENITH_ORACLE_USER_AUTHORIZATION=${ZENITH_INFRA_ORACLE_USER_AUTHORIZATION:-}

    ZENITH_ORACLE_PASSWORD_AI=${ZENITH_INFRA_ORACLE_PASSWORD_AI:-}
    ZENITH_ORACLE_PASSWORD_DIRECTORY=${ZENITH_INFRA_ORACLE_PASSWORD_DIRECTORY:-}
    ZENITH_ORACLE_PASSWORD_TENANT=${ZENITH_INFRA_ORACLE_PASSWORD_TENANT:-}
    ZENITH_ORACLE_PASSWORD_IDP=${ZENITH_INFRA_ORACLE_PASSWORD_IDP:-}
    ZENITH_ORACLE_PASSWORD_PORTAL=${ZENITH_INFRA_ORACLE_PASSWORD_PORTAL:-}
    ZENITH_ORACLE_PASSWORD_PORTALRT=${ZENITH_INFRA_ORACLE_PASSWORD_PORTALRT:-}
    ZENITH_ORACLE_PASSWORD_PRS=${ZENITH_INFRA_ORACLE_PASSWORD_PRS:-}
    ZENITH_ORACLE_PASSWORD_STUDIO=${ZENITH_INFRA_ORACLE_PASSWORD_STUDIO:-}
    ZENITH_ORACLE_PASSWORD_PROCESS_ENGINE=${ZENITH_INFRA_ORACLE_PASSWORD_PROCESS_ENGINE:-}
    ZENITH_ORACLE_PASSWORD_PROCESS_ENGINE_ROOT=${ZENITH_INFRA_ORACLE_PASSWORD_PROCESS_ENGINE_ROOT:-}
    ZENITH_ORACLE_PASSWORD_METRICS=${ZENITH_INFRA_ORACLE_PASSWORD_METRICS:-}
    ZENITH_ORACLE_PASSWORD_POLICY=${ZENITH_INFRA_ORACLE_PASSWORD_POLICY:-}
    ZENITH_ORACLE_PASSWORD_MOBIUS=${ZENITH_INFRA_ORACLE_PASSWORD_MOBIUS:-}
    ZENITH_ORACLE_PASSWORD_MOBIUSVIEW=${ZENITH_INFRA_ORACLE_PASSWORD_MOBIUSVIEW:-}
    ZENITH_ORACLE_PASSWORD_EVENTANALYTICS=${ZENITH_INFRA_ORACLE_PASSWORD_EVENTANALYTICS:-}
    ZENITH_ORACLE_PASSWORD_AUTHORIZATION=${ZENITH_INFRA_ORACLE_PASSWORD_AUTHORIZATION:-}
}

set_database_settings() {
    external_database=false
    ZENITH_DATABASE_HOST=${ZENITH_DATABASE_HOST:-}

    if [ "$ZENITH_STAGE" != "infra" ]; then
        if [ "$ZENITH_DATABASE_HOST" != "" ]; then
            external_database=true;
            set_database_common_settings;
            set_postgresql_settings;
            set_oracle_settings;
        else
            set_database_common_infra_settings;
            set_postgresql_infra_settings;
            set_oracle_infra_settings;
        fi
    else
        if [ "$ZENITH_DATABASE_HOST" != "" ]; then
            external_database=true;
        fi

        set_database_common_settings;
        set_postgresql_settings;
        set_oracle_settings;
    fi
}

set_kafka_settings() {
    KAFKA_ENABLED=${KAFKA_ENABLED:-false};
    KAFKA_NAMESPACE="${KAFKA_NAMESPACE:-shared}";
    KAFKA_VOLUME=`eval echo $KAFKA_VOLUME`;
    KAFKA_CONF_FILE=kafka-statefulset.yaml;
    KAFKA_VERSION="${KAFKA_VERSION:-3.3.1-debian-11-r3}";
    KAFKA_STORAGE_FILE=kafka-storage.yaml;
}

set_configuration() {
    skip_cluster_creation=false
    ZENITH_KUBECONFIG="${ZENITH_KUBECONFIG:-}"

    if [ "$ZENITH_KUBECONFIG" != "" ] || [ "$ZENITH_KUBERNETES_TYPE" == "rosa" ] || [ "$ZENITH_KUBERNETES_TYPE" == "crc" ] || [ "$ZENITH_KUBERNETES_TYPE" == "okd" ]; then
        skip_cluster_creation=true
    else 
        ZENITH_KUBECONFIG=${ZENITH_INFRA_KUBECONFIG:-}
    fi

    set_kafka_settings;
    set_local_registry_default_settings;
    set_public_registry_credentials;
    set_docker_credentials;
    set_domain_settings;
    set_database_settings;
    set_mobius_settings;
    set_secret_configuration;
    set_emu_settings;
    set_studio_settings;
    set_cluster_settings;

    ZENITH_DISABLE_MOBIUS=${ZENITH_DISABLE_MOBIUS:-false}
    ZENITH_DNS_SERVER="${ZENITH_DNS_SERVER:-}"
    ZENITH_CUSTOM_THEME="${ZENITH_CUSTOM_THEME:-}"

    ZENITH_AWS_REGION="${ZENITH_AWS_REGION:-us-east-1}"
    ZENITH_AWS_ACCESS_KEY="${ZENITH_AWS_ACCESS_KEY:-}"
    ZENITH_AWS_SECRET_KEY="${ZENITH_AWS_SECRET_KEY:-}"
    ZENITH_AWS_ACCOUNT="${ZENITH_AWS_ACCOUNT:-375537116202}"
    VALIDATE_DEPLOYMENT=${VALIDATE_DEPLOYMENT:-true}
}

set_secret_configuration() {
    ASG_DIRECTORY_SERVICE_SECRET_NAME="${ASG_DIRECTORY_SERVICE_SECRET_NAME:-notset}"
    ASG_DIRECTORY_SERVICE_SECRET_VALUE="${ASG_DIRECTORY_SERVICE_SECRET_VALUE:-notset}"
    ASG_DIRECTORY_SERVICE_REDIS_SECRET_VALUE="${ASG_DIRECTORY_SERVICE_REDIS_SECRET_VALUE:-notset}"

    ASG_AI_SERVICES_FRAMEWORK_SECRET_NAME="${ASG_AI_SERVICES_FRAMEWORK_SECRET_NAME:-notset}"
    ASG_AI_SERVICES_FRAMEWORK_SECRET_VALUE="${ASG_AI_SERVICES_FRAMEWORK_SECRET_VALUE:-notset}"
    
    ASG_PORTAL_SECRET_NAME="${ASG_PORTAL_SECRET_NAME:-notset}"
    ASG_PORTAL_SECRET_VALUE="${ASG_PORTAL_SECRET_VALUE:-notset}"
    ASG_PORTAL_REALTIME_SECRET_VALUE="${ASG_PORTAL_REALTIME_SECRET_VALUE:-notset}"
    ASG_PORTAL_REDIS_SECRET_VALUE="${ASG_PORTAL_REDIS_SECRET_VALUE:-notset}"

    ASG_PRS_SECRET_NAME="${ASG_PRS_SECRET_NAME:-notset}"
    ASG_PRS_SECRET_VALUE="${ASG_PRS_SECRET_VALUE:-notset}"
    ASG_PRS_STORE_SECRET_VALUE="${ASG_PRS_STORE_SECRET_VALUE:-notset}"

    ASG_PROCESS_ENGINE_SECRET_NAME="${ASG_PROCESS_ENGINE_SECRET_NAME:-notset}"
    ASG_PROCESS_ENGINE_SECRET_VALUE="${ASG_PROCESS_ENGINE_SECRET_VALUE:-notset}"
    ASG_PROCESS_ENGINE_STORE_SECRET_VALUE="${ASG_PROCESS_ENGINE_STORE_SECRET_VALUE:-notset}"

    ASG_STUDIO_SECRET_NAME="${ASG_STUDIO_SECRET_NAME:-notset}"
    ASG_STUDIO_SECRET_VALUE="${ASG_STUDIO_SECRET_VALUE:-notset}"
    ASG_STUDIO_STORE_SECRET_VALUE="${ASG_STUDIO_STORE_SECRET_VALUE:-notset}"

    ASG_TENANT_SERVICE_SECRET_NAME="${ASG_TENANT_SERVICE_SECRET_NAME:-notset}"
    ASG_TENANT_SERVICE_SECRET_VALUE="${ASG_TENANT_SERVICE_SECRET_VALUE:-notset}"
    ASG_TENANT_SERVICE_REDIS_SECRET_VALUE="${ASG_TENANT_SERVICE_REDIS_SECRET_VALUE:-notset}"

    ASG_TOKEN_SERVICE_SECRET_NAME="${ASG_TOKEN_SERVICE_SECRET_NAME:-notset}"
    ASG_TOKEN_SERVICE_SECRET_VALUE="${ASG_TOKEN_SERVICE_SECRET_VALUE:-notset}"

    ASG_CONSOLE_SERVICE_SECRET_NAME="${ASG_CONSOLE_SERVICE_SECRET_NAME:-notset}"
    ASG_CONSOLE_SERVICE_REDIS_SECRET_VALUE="${ASG_CONSOLE_SERVICE_REDIS_SECRET_VALUE:-notset}"
    ASG_CONSOLE_SERVICE_RABBITMQ_SECRET_VALUE="${ASG_CONSOLE_SERVICE_RABBITMQ_SECRET_VALUE:-notset}"

    ASG_MOBIUS_SECRET_NAME="${ASG_MOBIUS_SECRET_NAME:-notset}"
    ASG_MOBIUS_DB_PASSWORD_SECRET_VALUE="${ASG_MOBIUS_DB_PASSWORD_SECRET_VALUE:-notset}"
    ASG_MOBIUS_DB_USER_SECRET_VALUE="${ASG_MOBIUS_DB_USER_SECRET_VALUE:-notset}"
    ASG_MOBIUS_DB_ENDPOINT_SECRET_VALUE="${ASG_MOBIUS_DB_ENDPOINT_SECRET_VALUE:-notset}"
    ASG_MOBIUS_DB_PORT_SECRET_VALUE="${ASG_MOBIUS_DB_PORT_SECRET_VALUE:-notset}"
    ASG_MOBIUS_DB_SCHEMA_SECRET_VALUE="${ASG_MOBIUS_DB_SCHEMA_SECRET_VALUE:-notset}"    

    ASG_MOBIUSVIEW_SECRET_NAME="${ASG_MOBIUSVIEW_SECRET_NAME:-notset}"
    ASG_MOBIUSVIEW_DB_URL_SECRET_VALUE="${ASG_MOBIUSVIEW_DB_URL_SECRET_VALUE:-notset}"
    ASG_MOBIUSVIEW_DB_USER_SECRET_VALUE="${ASG_MOBIUSVIEW_DB_USER_SECRET_VALUE:-notset}"
    ASG_MOBIUSVIEW_DB_PASSWORD_SECRET_VALUE="${ASG_MOBIUSVIEW_DB_PASSWORD_SECRET_VALUE:-notset}"    
    
    ASG_EVENTANALYTICS_SECRET_NAME="${ASG_EVENTANALYTICS_SECRET_NAME:-notset}"
    ASG_EVENTANALYTICS_DB_URL_SECRET_VALUE="${ASG_EVENTANALYTICS_DB_URL_SECRET_VALUE:-notset}"
    ASG_EVENTANALYTICS_DB_USER_SECRET_VALUE="${ASG_EVENTANALYTICS_DB_USER_SECRET_VALUE:-notset}"
    ASG_EVENTANALYTICS_DB_PASSWORD_SECRET_VALUE="${ASG_EVENTANALYTICS_DB_PASSWORD_SECRET_VALUE:-notset}"    


    ASG_AUTHORIZATION_SECRET_NAME="${ASG_AUTHORIZATION_SECRET_NAME:-notset}"
    ASG_AUTHORIZATION_DB_URL_SECRET_VALUE="${ASG_AUTHORIZATION_DB_URL_SECRET_VALUE:-notset}"
    ASG_AUTHORIZATION_DB_USER_SECRET_VALUE="${ASG_AUTHORIZATION_DB_USER_SECRET_VALUE:-notset}"
    ASG_AUTHORIZATION_DB_PASSWORD_SECRET_VALUE="${ASG_AUTHORIZATION_DB_PASSWORD_SECRET_VALUE:-notset}"


    ASG_POLICY_SECRET_NAME="${ASG_POLICY_SECRET_NAME:-notset}"
    ASG_POLICY_DB_URL_SECRET_VALUE="${ASG_POLICY_DB_URL_SECRET_VALUE:-notset}"
    ASG_POLICY_DB_USER_SECRET_VALUE="${ASG_POLICY_DB_USER_SECRET_VALUE:-notset}"
    ASG_POLICY_DB_PASSWORD_SECRET_VALUE="${ASG_POLICY_DB_PASSWORD_SECRET_VALUE:-notset}"


    ASG_METRIC_SECRET_NAME="${ASG_METRIC_SECRET_NAME:-notset}"
    ASG_METRIC_DB_URL_SECRET_VALUE="${ASG_METRIC_DB_URL_SECRET_VALUE:-notset}"
    ASG_METRIC_DB_USER_SECRET_VALUE="${ASG_METRIC_DB_USER_SECRET_VALUE:-notset}"
    ASG_METRIC_DB_PASSWORD_SECRET_VALUE="${ASG_METRIC_DB_PASSWORD_SECRET_VALUE:-notset}"

    AUTOMATIONNEXT_SECRET_NAME_CIQ_WEB="${AUTOMATIONNEXT_SECRET_NAME_CIQ_WEB:-}"
    AUTOMATIONNEXT_SECRET_VALUE_CIQ_WEB_DB_PASSWORD="${AUTOMATIONNEXT_SECRET_VALUE_CIQ_WEB_DB_PASSWORD:-password}"
}	

set_public_registry_credentials() {
    if [ "$ZENITH_REGISTRY_TYPE" == "public" ]; then
        echo You need to enter the credentials to access the public registry
        read -p "Username: " registry_username;
        read -sp "Password: " registry_password;
    fi
}

set_docker_credentials() {
    ZENITH_DOCKER_PASSWORD="${DOCKER_PASSWORD:-}"

    if [[ "$DOCKER_USERNAME" != "" && "$ZENITH_DOCKER_PASSWORD" == "" ]]; then
        echo "We detected that you configured a DOCKER_USERNAME to use authenticated calls to the Docker Hub.";
        echo "For that reason, you need to insert your password to access Docker Hub with the $DOCKER_USERNAME username.";
        read -sp "Password: " DOCKER_PASSWORD;
        echo "";
    else
        DOCKER_PASSWORD=$ZENITH_DOCKER_PASSWORD
    fi
}

set_cluster_settings() {
    ZENITH_NAMESPACE="${ZENITH_NAMESPACE:-zenith}";
    DATABASE_NAMESPACE="${DATABASE_NAMESPACE:-shared}";
    KAFKA_NAMESPACE="${KAFKA_NAMESPACE:-shared}";
    EMU_NAMESPACE="${EMU_NAMESPACE:-shared}";
    ISTIO_CONF_VERSION="${ISTIO_CONF_VERSION:-1.16.1}";

    KUBE_CLUSTER_NAME="${CLUSTER_NAME:-zenith}";
    KUBE_VOLUME_PATH="${ZENITH_IDP_CERTS_PATH:-~/data/certs}";
    KUBE_VOLUME_PATH="${KUBE_VOLUME_PATH/\~/$HOME}";
    TRUSTSTORE_VOLUME_PATH="${ZENITH_TRUSTSTORE_CERTS_PATH:-~/data/truststore-certs}";
    TRUSTSTORE_VOLUME_PATH="${TRUSTSTORE_VOLUME_PATH/\~/$HOME}";

    KUBE_REGISTRY_NAME="k3d-${ZENITH_LOCALREGISTRY_NAME:-zenith-registry}";
    KUBE_REGISTRY_PORT="${ZENITH_LOCALREGISTRY_PORT:-5000}";
    KUBE_NUM_AGENTS="${KUBE_AGENTS:-2}";
    KUBE_REGISTRY="--registry-use http://${KUBE_REGISTRY_NAME}:${KUBE_REGISTRY_PORT}";

    istio_set_cluster_ports;
    automationnext_set_cluster_ports;
    KUBE_PORTS="--port 8080:8080@loadbalancer --port ${ZENITH_PORT}:${ZENITH_PORT}@loadbalancer ${ISTIO_CLUSTER_PORTS} ${AUTOMATIONNEXT_PORTS}";
    idp_volume_path=$(get_idp_volume);
    truststore_volume_path=$(get_truststore_volume);

    if [ "$KAFKA_ENABLED" == "true" ]; then
        kafka_volume=$(get_kafka_volume);
        KUBE_ARGS="--volume $idp_volume_path:$idp_volume_path --volume $truststore_volume_path:$truststore_volume_path --volume $kafka_volume:$kafka_volume --wait ${KUBE_PORTS}"
    else
        KUBE_ARGS="--volume $idp_volume_path:$idp_volume_path --volume $truststore_volume_path:$truststore_volume_path --wait ${KUBE_PORTS}"
    fi
}

set_local_registry_default_settings() {
    ZENITH_LOCALREGISTRY_AWSPROFILE="{$ZENITH_LOCALREGISTRY_AWSPROFILE:-}"
    ZENITH_LOCALREGISTRY_SOURCE_REGISTRY="{$ZENITH_LOCALREGISTRY_SOURCE_REGISTRY:-}"
    ZENITH_LOCALREGISTRY_CREATE="{$ZENITH_LOCALREGISTRY_CREATE:-}"
    ZENITH_LOCALREGISTRY_PUSH_IMAGES="{$ZENITH_LOCALREGISTRY_PUSH_IMAGES:-}"
    ZENITH_LOCALREGISTRY_NAME="{$ZENITH_LOCALREGISTRY_NAME:-}"
    ZENITH_LOCALREGISTRY_DNS="{$ZENITH_LOCALREGISTRY_DNS:-}"
    ZENITH_LOCALREGISTRY_PORT="{$ZENITH_LOCALREGISTRY_PORT:-}"
}

set_domain_settings() {
    if [ "$ZENITH_KUBERNETES_TYPE" == "okd" ]; then
        RANDOM_STRING=$(xxd -l 6 -c 32 -p < /dev/random)
        ZENITH_DOMAIN="dev-$RANDOM_STRING.asg.dev"
        ZENITH_PORT=${ZENITH_PORT:-443}
        ZENITH_HTTP_PORT=${ZENITH_HTTP_PORT:-80}
    elif [ "$ZENITH_KUBERNETES_TYPE" == "rosa" ]; then
        BASE_DOMAIN=$(oc get ingresses.config/cluster -o jsonpath={.spec.domain})
        ZENITH_DOMAIN="route-zenith.$BASE_DOMAIN"
        ZENITH_PORT=8443
        ZENITH_HTTP_PORT=8080
    elif [ "$ZENITH_KUBERNETES_TYPE" == "eks" ]; then
        if [ "$skip_cluster_creation" == "false" ]; then
            ZENITH_DOMAIN="dev-$ZENITH_EKS_ID-$ZENITH_EKS_USERNAME.asg.dev"
            ZENITH_PORT=8443
            ZENITH_HTTP_PORT=8080
        else
            ZENITH_DOMAIN="${ZENITH_DOMAIN:-$(hostname --fqdn)}"
            ZENITH_PORT=${ZENITH_PORT:-8443}
            ZENITH_HTTP_PORT=${ZENITH_HTTP_PORT:-8080}
        fi
    elif [ "$ZENITH_KUBERNETES_TYPE" == "crc" ]; then
        ZENITH_DOMAIN="${ZENITH_DOMAIN:-$(hostname --fqdn)}"
        ZENITH_PORT=${ZENITH_PORT:-443}
        ZENITH_HTTP_PORT=${ZENITH_HTTP_PORT:-80}	
    else
        ZENITH_DOMAIN="${ZENITH_DOMAIN:-$(hostname --fqdn)}"
        ZENITH_PORT=${ZENITH_PORT:-8443}
        ZENITH_HTTP_PORT=${ZENITH_HTTP_PORT:-8080}
    fi
}

set_emu_settings() {
    JVMAINFRAME_ENABLE="${JVMAINFRAME_ENABLE:-false}"
}

set_studio_settings() {
    if [ "$ZENITH_SERVICE_STUDIO_ENABLED" == "true" ]; then
        DEVELOPER_USERNAME="developer"
    else
        # Setting this to empty, will avoid seeding the developer user
        DEVELOPER_USERNAME=""
    fi
}
