kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mobius-pv-claim-dev
  namespace: dev
  annotations:
    volume.beta.kubernetes.io/storage-class: efs
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000M
  volumeName: mobius-pv-storage-dev
