# Override values.yaml

global:
  storageClass: "microk8s-hostpath"
  postgresql:
    auth:
      postgresPassword: "postgres"

primary:
  initdb:
    scripts: {
      create-databases.sql:
        CREATE ROLE "mobiusserver" WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION CONNECTION LIMIT -1 PASSWORD 'postgres';
        CREATE ROLE "mobiusview" WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION CONNECTION LIMIT -1 PASSWORD 'postgres';
        CREATE ROLE "eventanalytics" WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION CONNECTION LIMIT -1 PASSWORD 'postgres';
        CREATE DATABASE "mobiusserver" WITH OWNER = "mobiusserver" TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'C' LC_CTYPE = 'C' TABLESPACE = pg_default CONNECTION LIMIT = -1;
        CREATE DATABASE "mobiusview" WITH OWNER = "mobiusview" TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'C' LC_CTYPE = 'C' TABLESPACE = pg_default CONNECTION LIMIT = -1;
        CREATE DATABASE "eventanalytics" WITH OWNER = "eventanalytics" TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'C' LC_CTYPE = 'C' TABLESPACE = pg_default CONNECTION LIMIT = -1;
        CREATE DATABASE keycloak;
    }

  service:
    type: NodePort
    nodePorts:
      postgresql: "30002"