apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventanalytics.fullname" . }}
  labels:
    {{- include "eventanalytics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.ports.targetPort }}
      protocol: {{ .Values.ports.protocol }}
      name: {{ .Values.ports.name }}
  selector:
    {{- include "eventanalytics.selectorLabels" . | nindent 4 }}
