apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mobius12-efs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mobius12-diagnose
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi