apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mobius12-efs
  namespace: mobius-sales
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mobius12-diagnose
  namespace: mobius-sales
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi


