version: '3'

services:
  mobius-demo:
    image: registry.rocketsoftware.com/mobius_demo:12.1.0
    restart: "no"
    #command: "/bin/sh -c /home/demo/delete_demo.sh"
    environment:
      MV_URL: "http://mobiusview:8080/mobius"
      MV_REPOSITORY: "Mobius"
      MV_BASIC_AUTH_USER: "admin"
      # MV_BASIC_AUTH_PASS -> admin encrypted with MV_SECRET_SEC file $HOME/asg/security/secret.sec
      MV_BASIC_AUTH_PASS: "ASG_ENC(IzrmGPXQqWV3/d6f1kq/Bw==)"
      MV_SECRET_SEC: "5##)MbIPy?%_vFx*5Cm0G15MLc0rV/SK.cY"
      MV_DEMO_DEFINITIONS: "./_XML/CreateAllDataSamplerStructures.xml"
      MV_DEMO_LOAD_DATA: "./_XML/LoadAllDataSamplerContents.xml"
    networks:
      - mobius12_default
    volumes:
      - mobius12_mobius-data:/mnt/efs
      
networks:
  mobius12_default:
    external: true
    
volumes:
  mobius12_mobius-data:
    external: true    


